---
- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: '{{ docker_users }}'

- name: Reset ssh connection to apply users changes
  meta: reset_connection
