---
- name: Run portainer agent
  become: false
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:latest
    restart_policy: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
