---
- name: Install docker packages
  block:
    - name: Install Docker engine
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
