---
- name: Make sure docker-compose is not installed via apt
  ansible.builtin.package:
    name: docker-compose
    state: absent
  when: ansible_os_family == "Debian"

- name: Check if previous docker-compose binary is installed
  ansible.builtin.command: 'which docker-compose'
  register: docker_compose_binary
  failed_when: false
  ignore_errors: true

- name: Remove previous docker-compose binary if it already exists
  when: docker_compose_binary.stdout | length > 0
  ansible.builtin.file:
    path: "{{ docker_compose_binary.stdout }}"
    state: absent

- name: Get latest docker-compose version
  ansible.builtin.shell: 'git ls-remote --refs --sort="version:refname" --tags https://github.com/docker/compose | cut -d / -f3- | tail -n 1'
  register: docker_compose_version

- name: Download latest docker-compose binary
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: a+x

# - name: Install docker-compose Python package
#   community.general.pipx:
#     name: docker-compose
#     install_deps: true
#     install_apps: true
#   become: false
