---
- name: Remove old Docker installation
  ansible.builtin.include_tasks: remove_old_install.yml

- name: Install dependencies
  ansible.builtin.include_tasks: install_dependencies.yml

- name: Add Docker repository
  ansible.builtin.include_tasks: add_docker_repository.yml

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml

- name: Install Docker Compose V1
  ansible.builtin.include_tasks: install_docker_compose_v1.yml
  when: install_compose_v1

- name: Add users to Docker group
  ansible.builtin.include_tasks: add_docker_users.yml

- name: Deploy Portainer Agent
  ansible.builtin.include_tasks: portainer_agent.yml
  when: portainer_agent
