---
- name: Remove old Docker installation
  ansible.builtin.include_tasks: remove_old_install.yml

- name: Install dependencies
  ansible.builtin.include_tasks: install_dependencies.yml

- name: Add Docker repository
  ansible.builtin.include_tasks: add_docker_repository.yml

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml

- name: Install Docker Compose
  ansible.builtin.include_tasks: install_docker_compose.yml

- name: Add users to Docker group
  ansible.builtin.include_tasks: add_docker_users.yml
