---
- name: Ensure nfs-common is installed
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Ensure NFS mount point exists
  ansible.builtin.file:
    path: "{{ nfs_mount_path }}"
    state: directory
    mode: '0755'

- name: Mount NFS share and add to fstab
  ansible.posix.mount:
    src: "{{ nfs_src }}"
    path: "{{ nfs_mount_path }}"
    fstype: nfs
    opts: "{{ nfs_opts }}"
    dump: '0'
    passno: '0'
    state: mounted
