---
- name: Check if Docker already exist
  ansible.builtin.command: 'which docker'
  register: docker_exists
  failed_when: no
  ignore_errors: true
  changed_when: docker_exists.rc != 0

- name: Remove docker if already installed
  when: docker_exists.rc != 0
  block:
    - name: Update aptitude repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        autoclean: yes

    - name: Remove old Docker versions
      ansible.builtin.package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        purge: true
